//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pbl3_Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public string email { get; set; }
        public string pass_word { get; set; }
        public byte role { get; set; }
        public bool active { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual staff staff { get; set; }
    }
}
