//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pbl3_Cinema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaEntities : DbContext
    {
        public CinemaEntities()
            : base("name=CinemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<auditorium> auditoriums { get; set; }
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<detail_bill> detail_bill { get; set; }
        public virtual DbSet<movie> movies { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<rating> ratings { get; set; }
        public virtual DbSet<reservation> reservations { get; set; }
        public virtual DbSet<screening> screenings { get; set; }
        public virtual DbSet<seat> seats { get; set; }
        public virtual DbSet<seat_reserved> seat_reserved { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<user_infor> user_infor { get; set; }
    }
}
