//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pbl3_Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail_bill
    {
        public int bill_id { get; set; }
        public int product_id { get; set; }
        public int the_number_of_products { get; set; }
        public int price { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual product product { get; set; }
    }
}
