//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pbl3_Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movie()
        {
            this.ratings = new HashSet<rating>();
            this.screenings = new HashSet<screening>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> category_id { get; set; }
        public string description_movie { get; set; }
        public string director { get; set; }
        public string list_cast { get; set; }
        public int duration_min { get; set; }
        public System.DateTime release_date { get; set; }
        public System.DateTime expiration_date { get; set; }
        public byte[] poster { get; set; }
        public byte[] video_trailer { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rating> ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<screening> screenings { get; set; }
    }
}
