//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pbl3_Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reservation()
        {
            this.bills = new HashSet<bill>();
            this.seat_reserved = new HashSet<seat_reserved>();
        }
    
        public int id { get; set; }
        public string customer_id { get; set; }
        public string staff_id { get; set; }
        public Nullable<int> screening_id { get; set; }
        public System.DateTime booking_date { get; set; }
        public int pay { get; set; }
        public int discount_pay { get; set; }
        public int sum_pay { get; set; }
        public bool paid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill> bills { get; set; }
        public virtual customer customer { get; set; }
        public virtual screening screening { get; set; }
        public virtual staff staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seat_reserved> seat_reserved { get; set; }
    }
}
