//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pbl3_Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class screening
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public screening()
        {
            this.reservations = new HashSet<reservation>();
            this.seat_reserved = new HashSet<seat_reserved>();
        }
    
        public int id { get; set; }
        public int movie_id { get; set; }
        public int auditorium_id { get; set; }
        public System.DateTime show_day { get; set; }
        public System.TimeSpan show_time { get; set; }
        public int price { get; set; }
    
        public virtual auditorium auditorium { get; set; }
        public virtual movie movie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservation> reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seat_reserved> seat_reserved { get; set; }
    }
}
