//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pbl3_Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class seat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public seat()
        {
            this.seat_reserved = new HashSet<seat_reserved>();
        }
    
        public int id { get; set; }
        public int row_location { get; set; }
        public int column_location { get; set; }
        public Nullable<int> auditorium_id { get; set; }
    
        public virtual auditorium auditorium { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seat_reserved> seat_reserved { get; set; }
    }
}
