//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pbl3_Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class seat_reserved
    {
        public int seat_id { get; set; }
        public int screening_id { get; set; }
        public int reservation_id { get; set; }
    
        public virtual reservation reservation { get; set; }
        public virtual screening screening { get; set; }
        public virtual seat seat { get; set; }
    }
}
